// Generated by CoffeeScript 1.3.3

J.Core.RouteConfig = function() {
  J.App.Router.map(function() {
    this.resource("profile", function() {
      this.route("feed");
      return this.route("company");
    });
    this.resource("about");
    return this.resource("developers");
  });
  J.App.IndexRoute = Em.Route.extend({
    redirect: function() {
      return this.transitionTo("profile");
    }
  });
  J.App.ProfileRoute = Em.Route.extend({
    model: function() {
      return J.App.Profile.find(1);
    }
  });
  return J.App.ProfileIndexRoute = Em.Route.extend({
    redirect: function() {
      return this.transitionTo("profile.feed");
    }
  });
};
