// Generated by CoffeeScript 1.3.3
var J;

J = {
  Core: {},
  Controller: {},
  Model: {},
  View: {}
};

head.js("js/app/core/Store.js", "js/app/core/RouteConfig.js", "js/app/controller/ProfileController.js", "js/app/view/EditableTextField.js", "js/app/model/Profile.js", "js/app/template/Layout.js", "js/app/template/Profile.js", "js/app/template/Developers.js", "js/app/template/ProfileFeed.js", "js/app/template/ProfileCompany.js", "js/app/template/About.js", function() {
  J.App = Em.Application.create();
  J.Core.Store();
  J.Core.RouteConfig();
  J.Model.Profile();
  return J.Controller.ProfileController();
});
