// Generated by CoffeeScript 1.3.3

J.Controller.ProfileController = function() {
  return J.App.ProfileController = Em.ObjectController.extend({
    updateStatus: function(profile) {
      return profile.set("isStatusEditable", true);
    },
    statusUpdated: function(newValue, view) {
      var model;
      model = view.get("model");
      model.set("isStatusEditable", false);
      return model.get("transaction").commit();
    },
    rejectStatusUpdate: function(view) {
      var model;
      model = view.get("model");
      if (model.get("isStatusEditable")) {
        model.set("isStatusEditable", false);
        return model.get("transaction").rollback();
      }
    }
  });
};
