// Generated by CoffeeScript 1.3.3

J.View.EditableTextField = Em.TextField.extend({
  focusOut: function() {
    return this.get("controller").rejectStatusUpdate(this);
  },
  didInsertElement: function() {
    var el;
    el = $(this.get("element"));
    el.select();
    return el.focus();
  }
});
